name: build-and-test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      # Step 3: Install Chrome and ChromeDriver
      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest # Automatically installs the latest stable version of Chrome and its matching ChromeDriver

      # Step 4: Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Step 5: Build the project
      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      # Step 6: Run Tests
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal --configuration Release
