name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      # Install Chrome
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      # Install ChromeDriver
      - name: Install ChromeDriver
        run: sudo apt-get install -y chromedriver

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build the project
      - name: Build the project
        run: dotnet build --no-restore --configuration Debug

      # Run Tests
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
